# Generated by Django 5.2.11 on 2026-02-13 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_coachprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='coachprofile',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coachprofile',
            name='contract_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coachprofile',
            name='contract_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coachprofile',
            name='license_level',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='coachprofile',
            name='parent_contact_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='coachprofile',
            name='parent_occupation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='coachprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='coachprofile',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='coach_resumes/'),
        ),
        migrations.AddField(
            model_name='coachprofile',
            name='salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='coachprofile',
            name='signed_contract',
            field=models.FileField(blank=True, null=True, upload_to='coach_contracts/'),
        ),
    ]
